In [1]:
import tensorflow as tf
import numpy as np

In [2]:
sess = tf.InteractiveSession()

# Operations

In [3]:
const = tf.constant(10)

In [4]:
fill_mat = tf.fill((4,4),10)

In [5]:
zeros = tf.zeros((4,4))

In [6]:
ones = tf.ones((4,4))

In [7]:
random_init = tf.random_normal((4,4))

In [8]:
operations = [const, fill_mat, zeros, ones, zeros, random_init]

In [9]:
for op in operations:
    print(op.eval())
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[-1.25572824 -0.45239794  0.55463207  0.10220783]
 [ 1.64763308  0.69436395 -0.66816831 -0.77532285]
 [-1.13020575 -1.03106272 -0.81894922 -0.78053987]
 [ 0.59374917 -1.5827018  -1.23425519  3.52732038]]


